name: Build and Push Docker image for Appointment Service

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Appointment Service
        run: |
          cd appointment_service
          docker build -t dimuth94/appointment-service:latest .
      
      - name: Push Docker image for Appointment Service
        run: |
          docker push dimuth94/appointment-service:latest

      - name: Log out from Docker Hub
        run: docker logout
