name: Build and Push Docker image for Patient Record Service

on:
  push:
    branches:
      - master  # Trigger workflow only on push to the master branch
    paths:
      - 'patient_record_service/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for Patient Record Service
        run: |
          cd patient_record_service
          docker build -t dimuth94/patient-record-service:latest .
      
      - name: Push Docker image for Patient Record Service
        run: |
          docker push dimuth94/patient-record-service:latest

      - name: Log out from Docker Hub
        run: docker logout
